version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/ProceduralMiniGameGenerator.WebAPI/Dockerfile
      target: build
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - .:/src
      - ./backend/logs:/app/logs
    working_dir: /src/backend/ProceduralMiniGameGenerator.WebAPI
    command: dotnet watch run --urls=http://+:80
    networks:
      - app-network

  frontend:
    image: node:18-alpine
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge